name: C build

on:
  push:
  #   branches: ["master"]
  # pull_request:
  #   branches: ["master"]

jobs:
  make_check:
    strategy:
      matrix:
        os: [ubuntu-latest] # macOS-latest is disabled due to https://github.com/distcc/distcc/issues/524
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ConorMacBride/install-package@v1
        with:
          # Note: aclocal is packaged with automake in Homebrew, so we need it even though
          # we don't use automake.
          brew: automake popt gdb
          apt: clang libavahi-client-dev libiberty-dev libpopt-dev gdb python3-dev python3-setuptools
          # brew-cask: TODO
          # choco: TODO
      - run: ./autogen.sh
      - run: ./configure
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
      - run: ./configure --without-libiberty
        if: ${{ startsWith(matrix.os, 'macOS') }}
      - run: make
      - run: make check
